version: '3'
services:
  web:
    image: gschauhan/sit737-2024-t1-prac5p:latest
    ports:
      - "3000:3000"

    healthcheck:
      test: ["CMD", "curl", "-f", http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
